In [22]:
import jax, jax.numpy as jnp
a = jnp.array([
    [1, 2],
    [3, 4]
])
def rot_boards(board):
    def rot(a, _):
        a = jnp.rot90(a)
        return a, a  # carry, y
    
    _, boards = jax.lax.scan(rot, board, jnp.arange(4, dtype=jnp.int32))
    return boards
a1 = rot_boards(a)
a2 = rot_boards(a)

a = jnp.concatenate([a1, a2], axis=0)
a

Array([[[2, 4],
        [1, 3]],

       [[4, 3],
        [2, 1]],

       [[3, 1],
        [4, 2]],

       [[1, 2],
        [3, 4]],

       [[2, 4],
        [1, 3]],

       [[4, 3],
        [2, 1]],

       [[3, 1],
        [4, 2]],

       [[1, 2],
        [3, 4]]], dtype=int32)

In [21]:
a = a.reshape(8, -1)
a

Array([[2, 4, 1, 3],
       [4, 3, 2, 1],
       [3, 1, 4, 2],
       [1, 2, 3, 4],
       [2, 4, 1, 3],
       [4, 3, 2, 1],
       [3, 1, 4, 2],
       [1, 2, 3, 4]], dtype=int32)

In [13]:
action = ["up", "right", "down", "left"]
lr_flip_action = ["up", "left", "down", "right"]
def action_rot90(li):
    first = li[0]
    return li[1:] + [first]

a = a
rl_flip_a = jnp.fliplr(a)

In [14]:
for i in range(4):
    print(a, action)
    print(rl_flip_a, lr_flip_action)
    a = jnp.rot90(a)
    rl_flip_a = jnp.rot90(rl_flip_a)
    action = action_rot90(action)
    lr_flip_action = action_rot90(lr_flip_action)

[[1 2]
 [3 4]] ['up', 'right', 'down', 'left']
[[2 1]
 [4 3]] ['up', 'left', 'down', 'right']
[[2 4]
 [1 3]] ['right', 'down', 'left', 'up']
[[1 3]
 [2 4]] ['left', 'down', 'right', 'up']
[[4 3]
 [2 1]] ['down', 'left', 'up', 'right']
[[3 4]
 [1 2]] ['down', 'right', 'up', 'left']
[[3 1]
 [4 2]] ['left', 'up', 'right', 'down']
[[4 2]
 [3 1]] ['right', 'up', 'left', 'down']


In [6]:
jnp.rot90(a, k=2)

Array([[4, 3],
       [2, 1]], dtype=int32)

In [7]:
# flip left-right
jnp.fliplr(a)

Array([[2, 1],
       [4, 3]], dtype=int32)